export const CURRENT_LOCATION = "CURRENT_LOCATION";
export const DESIRED_LOCATION = "DESIRED_LOCATION";
export const DESTINATION_LOCATION = "DESTINATION_LOCATION";
export const PLACEHOLDER = "PLACEHOLDER";
